# Generated by Django 5.2 on 2025-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('meat', '肉類'), ('vegetable', '蔬菜類'), ('seafood', '海鮮類'), ('fruit', '水果類'), ('other', '其他')], default='other', max_length=20),
        ),
    ]
